# *Questions*

In [2]:
import numpy as np

### *Valid Sudoku*

In [3]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [4]:
flag = True
for i in s:
    if np.sum(i) != 45:
        print("Not a valid Sudoku.")
        flag = False
        break
for i in s.T:
    if not flag:
        break
    if np.sum(i) != 45:
        print("Not a valid Sudoku.")
        flag = False
        break
if flag == True:
    print("Above sudoku is a valid sudoku")

Above sudoku is a valid sudoku


In [5]:
s.sum(axis=0)

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [6]:
np.sum(s, axis=0)

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [7]:
r = np.sum(s, axis=0)
if(len(r[r == 45])) == 9:
    c = np.sum(s, axis=1)
    if len(c[c==45] == 9):
        print("Its a valid sudoku")
    else:
        print("Not a valid sudoku")
else:
    print("Not a valid sudoku")

Its a valid sudoku


In [8]:
len(r == 45)

9

In [12]:
b = []
b.append(np.sum(s[:3, :3]))
b.append(np.sum(s[3:6, :3]))
b.append(np.sum(s[6:, :3]))
b.append(np.sum(s[:3, 3:6]))
b.append(np.sum(s[3:6, 3:6]))
b.append(np.sum(s[6:, 3:6]))
b.append(np.sum(s[:3, 6:]))
b.append(np.sum(s[3:6, 6:]))
b.append(np.sum(s[6:, 6:]))

<class 'list'>


In [66]:
s[6:, 6:]

array([[2, 8, 4],
       [6, 3, 5],
       [1, 7, 9]])

In [ ]:
def validSudoku(s):
    flag = True
    b = np.sum(s)
    for i in b:
        if i != 45:
            flag = False
            print("Row-wise Sudoku is not valid.")
            break
        else:
            print("Row-wise Sudoku is valid.")
    if flag:
        c = np.sum(s, axis=1)
        for j in c:
            if j != 45:
                flag = False
                print("Column-wise Sudoku is not valid.")
                break
            else:
                print("Column-wise Sudoku is valid.")

    if flag:
        sm = np.zeros((3, 3))
        

In [11]:
sm = np.zeros((3, 3))
sm += 45
sm

array([[45., 45., 45.],
       [45., 45., 45.],
       [45., 45., 45.]])

In [94]:
a = np.hsplit(s, 3)
b = np.vsplit(s, 3)
b

[array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
        [6, 7, 2, 1, 9, 5, 3, 4, 8],
        [1, 9, 8, 3, 4, 2, 5, 6, 7]]),
 array([[8, 5, 9, 7, 6, 1, 4, 2, 3],
        [4, 2, 6, 8, 5, 3, 7, 9, 1],
        [7, 1, 3, 9, 2, 4, 8, 5, 6]]),
 array([[9, 6, 1, 5, 3, 7, 2, 8, 4],
        [2, 8, 7, 4, 1, 9, 6, 3, 5],
        [3, 4, 5, 2, 8, 6, 1, 7, 9]])]

## *General Questions*

In [2]:
import numpy as np

In [73]:
data = np.array([
    [18, 85, 78],
    [19, 92, 88],
    [17, 76, 95],
    [18, 65, 70],
    [20, 90, 85]
])

In [4]:
# get the shape of the matrix
data.shape

(5, 3)

In [27]:
# find the average age of students
columns = np.hsplit(data, 3)
print("Average Age :", np.mean(columns[0]))

Average Age : 18.4


In [29]:
# Extract Maths Marks of all students
print("Maths Marks :\n", columns[1])

Maths Marks :
 [[85]
 [92]
 [76]
 [65]
 [90]]


In [31]:
# find the highest Science Marks
print("Highest marks in science subject is :", np.max(columns[2]))

Highest marks in science subject is : 95


In [65]:
# get details of the student who scored more than 90 in Maths
data[data[:, 1] > 90]

array([[19, 92, 88]])

In [67]:
# increase Maths marks of all students by 5
data[:, 1] += 5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [47]:
# find how many students are younger than 19
len(data[data[:, 0] < 19])

3

In [48]:
# calculate the average marks in each subject (column-wise mean)
print("Maths avg :",np.mean(columns[1]))
print("Science avg :", np.mean(columns[2]))

Maths avg : 86.6
Science avg : 83.2


In [50]:
np.mean(data[:, 1:], axis=0)

array([86.6, 83.2])

In [57]:
# get data of students who scored at least 80 in both subjects
data[(data[:, 1] >= 80 ) & (data[:, 2] >= 80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [74]:
# replace all Science marks < 75 with 0
data[:, 2][data[:, 2] < 75] = 0

In [75]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])