In [1]:
import numpy as np

# *Array Operations*

### *Arithmetic Operations*

In [2]:
a1 = np.arange(1, 6)
a2 = np.arange(6, 11)
print(a1, a2)

[1 2 3 4 5] [ 6  7  8  9 10]


In [3]:
add = a1 + a2
add

array([ 7,  9, 11, 13, 15])

In [4]:
sub = a1 - a2
sub

array([-5, -5, -5, -5, -5])

In [5]:
mul = a1 * a2
mul

array([ 6, 14, 24, 36, 50])

In [6]:
power = a1 ** a2
power

array([      1,     128,    6561,  262144, 9765625])

In [7]:
div = a1 / a2
div

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [9]:
fldiv = a1 // a2
fldiv

array([0, 0, 0, 0, 0])

### *Broadcasting*

In [12]:
l = [10, 20, 30, 40]
arr = np.array(l)

In [11]:
for i in range(len(l)):
    l[i] += 10
l

[20, 30, 40, 50]

In [13]:
arr += 10 #broadcasting adding 10 to each item of array
arr

array([20, 30, 40, 50])

In [15]:
a = np.arange(1, 26).reshape(5, 5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [16]:
a += 10
a 

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [17]:
a * 2

array([[22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50],
       [52, 54, 56, 58, 60],
       [62, 64, 66, 68, 70]])

### *Deep and shallow copy*

In [18]:
a = np.arange(1, 10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
slice  = a[:5]

In [20]:
slice = slice * 10
slice

# slice *= 10 will directly affect original a


array([10, 20, 30, 40, 50])

In [21]:
slice *= 10
slice

array([100, 200, 300, 400, 500])

In [22]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
a[4:6] * 10

array([50, 60])

In [25]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
b = a

In [27]:
b[0] = 99

In [28]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9])

In [29]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9])

In [30]:
b = a.copy() #shallow copy

In [31]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9])

In [32]:
b[0] = 1

In [33]:
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9])

In [35]:
a = [[1, 2],[3, 4]]
b = a.copy()
print(a)
print(b)

[[1, 2], [3, 4]]
[[1, 2], [3, 4]]


In [36]:
b[0].append(99)
print(a)
print(b)

[[1, 2, 99], [3, 4]]
[[1, 2, 99], [3, 4]]


In [38]:
import copy
m = [[1, 2],[3, 4]]
n = copy.deepcopy(m)
print(m)
print(n)

[[1, 2], [3, 4]]
[[1, 2], [3, 4]]


In [39]:
n[0].append(99)
print(m)
print(n)

[[1, 2], [3, 4]]
[[1, 2, 99], [3, 4]]


## *Matrix Operations*

In [40]:
A = np.array([[1, 2],[3, 4]])
B = np.array([[5, 6],[7, 8]])

In [41]:
A

array([[1, 2],
       [3, 4]])

In [42]:
B

array([[5, 6],
       [7, 8]])

In [43]:
prod = A*B
prod # each element is getting multiplicated to the respective element, not actually a matrix multiplication

array([[ 5, 12],
       [21, 32]])

In [44]:
prod = A @ B 
prod

array([[19, 22],
       [43, 50]])

In [45]:
prod = np.dot(A, B)
prod

array([[19, 22],
       [43, 50]])

In [46]:
A

array([[1, 2],
       [3, 4]])

In [47]:
A.T #Transpose

array([[1, 3],
       [2, 4]])

## *Advanced Array Manipulation*

In [48]:
A

array([[1, 2],
       [3, 4]])

In [49]:
B

array([[5, 6],
       [7, 8]])

#### *Stacking array*

In [50]:
a = np.arange(1, 5)
b = np.arange(5, 9)

In [51]:
a

array([1, 2, 3, 4])

In [52]:
b

array([5, 6, 7, 8])

In [54]:
np.vstack((a, b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [55]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [56]:
np.vstack((A, B))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [133]:
np.hstack((A, B))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [57]:
np.column_stack((a, b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

### *Splitting array*

In [58]:
c = np.arange(16).reshape(4, 4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [59]:
np.hsplit(c, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [60]:
a, b = np.hsplit(c, 2)
print(a)
print(b)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [61]:
np.hsplit(c, 4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [62]:
np.vsplit(c, 4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]