In [1]:
import numpy as np

## *Level 1: Basic Array Creation*

In [2]:
arr = np.array([5, 10, 15, 20, 25])
print(arr)

[ 5 10 15 20 25]


In [9]:
list0 = [1, "2", 3, "Hello"]
arr = np.array(list0)
print(arr)
arr.dtype

['1' '2' '3' 'Hello']


dtype('<U21')

In [10]:
arr = np.arange(1, 21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [11]:
arr = np.arange(2, 31, 2)
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [13]:
arr = np.array([1, 5, 7, 11, 15])
arr

array([ 1,  5,  7, 11, 15])

## *Level 2: Array Generation Functions*

In [14]:
arr = np.zeros(12)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
arr = np.zeros(20).reshape(4, 5)
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
arr = np.ones(12).reshape(3, 4)
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
arr = np.arange(50, 101, 5)
arr

array([ 50,  55,  60,  65,  70,  75,  80,  85,  90,  95, 100])

In [18]:
arr = np.linspace(0, 101, 11)
arr

array([  0. ,  10.1,  20.2,  30.3,  40.4,  50.5,  60.6,  70.7,  80.8,
        90.9, 101. ])

## *Level 3: Random Arrays*

In [20]:
arr = np.random.rand(10)
arr

array([0.90261968, 0.03182891, 0.5939379 , 0.06135655, 0.20188916,
       0.83641243, 0.08530682, 0.40636198, 0.0208869 , 0.89577034])

In [35]:
arr = np.random.randint(1, 101, size=(3, 4), dtype=int)
arr

array([[ 16,   3, 100,  20],
       [ 16,  96,  78,  83],
       [ 28,  35,  41,  89]], dtype=int32)

In [38]:
a = np.random.randint(1, 101)
a

8

In [47]:
arr = np.random.randint(50, 101, 20)
arr

array([71, 55, 74, 76, 91, 79, 80, 50, 79, 99, 60, 89, 94, 65, 91, 56, 89,
       96, 50, 89], dtype=int32)

In [46]:
arr = np.random.randint(1, 10, size=(5, 5))
arr

array([[7, 2, 2, 3, 3],
       [1, 1, 7, 9, 9],
       [4, 7, 9, 5, 2],
       [6, 1, 7, 5, 1],
       [9, 9, 4, 9, 1]], dtype=int32)

In [48]:
np.random.choice([10,20,30], size=5)

array([20, 30, 20, 20, 20])

## *Level 4: Array Attributes*

In [52]:
arr = np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [50]:
arr.shape

(5, 5)

In [51]:
arr.size

25

In [53]:
arr.dtype

dtype('int64')

In [54]:
arr.ndim

2

## *Level 5: Array Methods*

In [55]:
arr = np.arange(1,17).reshape(4,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [57]:
print(arr.min())

1


In [58]:
print(arr.max())

16


In [61]:
print(arr.sum())
print(np.sum(arr))

136
136


In [62]:
print(arr.mean())

8.5


In [63]:
print(arr.std())

4.6097722286464435


In [64]:
print(arr.argmax())

15


In [65]:
print(arr.argmin())

0


In [67]:
print(np.sum(arr, axis=1))

[10 26 42 58]


In [68]:
print(np.sum(arr, axis=0))

[28 32 36 40]


## *Level 6: Reshaping*

In [70]:
arr = np.random.randint(1, 24, size=(2, 12))
arr

array([[ 9, 23, 22, 14, 16,  8,  3, 11, 17,  6, 19, 20],
       [11, 14, 19,  8,  9, 18,  9, 12, 11, 14,  4,  1]], dtype=int32)

In [71]:
arr = np.random.randint(1, 24, size=(3, 8))
arr

array([[20, 16, 18, 21, 13,  3,  6, 19],
       [13,  7, 13, 23,  2,  3, 16, 16],
       [20,  7, 23, 20,  1, 14, 22, 13]], dtype=int32)

In [72]:
arr = np.random.randint(1, 24, size=(4, 6))
arr

array([[17,  3, 12, 12,  7, 16],
       [ 8,  6,  3, 10, 12,  9],
       [20, 18,  9,  9, 14, 20],
       [11,  8, 16, 18,  1, 17]], dtype=int32)

In [73]:
arr = np.random.randint(1, 24, size=(6, 4))
arr

array([[20,  7, 17, 11],
       [11,  3,  2, 16],
       [21, 11, 17, 15],
       [ 1, 17,  1,  4],
       [12, 16, 11, 14],
       [17, 23, 21, 18]], dtype=int32)

In [79]:
arr = np.random.randint(1, 37, size=(6, 6))
arr

array([[34, 33, 22, 28, 22, 20],
       [20, 19, 15,  4, 27, 19],
       [31, 24, 19, 33,  1, 10],
       [14, 10, 33, 22, 22, 30],
       [ 9, 14,  7,  7, 17, 35],
       [30, 25, 30, 17, 22, 30]], dtype=int32)

## *Level 7: Vector Indexing & Slicing*

In [92]:
arr = np.arange(11,31)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30])

In [83]:
print(arr[0])

11


In [84]:
print(arr[len(arr)-1])

30


In [87]:
print(arr[:5])

[11 12 13 14 15]


In [93]:
print(arr[13:])

[24 25 26 27 28 29 30]


In [94]:
print(arr[::2])

[11 13 15 17 19 21 23 25 27 29]


In [95]:
print(arr[2::3])

[13 16 19 22 25 28]


In [96]:
print(arr[5:13])

[16 17 18 19 20 21 22 23]


In [97]:
print(arr[::-1])

[30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11]


In [104]:
print(arr[::2][::-1])

[29 27 25 23 21 19 17 15 13 11]


## *Level 8: Matrix Indexing & Slicing*

In [105]:
arr = np.arange(1,37).reshape(6,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [106]:
arr[0]

array([1, 2, 3, 4, 5, 6])

In [107]:
arr[-1]

array([31, 32, 33, 34, 35, 36])

In [108]:
arr[:, 2]

array([ 3,  9, 15, 21, 27, 33])

In [109]:
arr[:, -1]

array([ 6, 12, 18, 24, 30, 36])

In [111]:
arr[:3]

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [112]:
arr[-2:]

array([[25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [113]:
arr[2:4, 2:4]

array([[15, 16],
       [21, 22]])

In [114]:
arr[:3, :3]

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [13, 14, 15]])

In [115]:
arr[-3:,-3:]

array([[22, 23, 24],
       [28, 29, 30],
       [34, 35, 36]])

In [116]:
arr[1:3, 1:3]

array([[ 8,  9],
       [14, 15]])

In [127]:
arr[[0,1,2,3,4,5], [0,1,2,3,4,5]]

array([ 1,  8, 15, 22, 29, 36])